name: mongoserver
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  args: ^1.6.0
  convert: '^2.0.1'
  crypto: ^2.1.5
  dart_style: '^1.0.10'
  http: ^0.12.2
  json_ast: '^1.0.5'
  jaguar_jwt: ^2.1.6
  mongo_dart: ^0.4.3
  mongo_dart_query: ^0.4.2
  
  runtime: ^1.0.0-9
  safe_config: ^2.0.2
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  password_hash: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  path: ^1.6.4