// This file is generated please do not edit this file

import 'package:mongoserver/models/index.dart';

class ModelRegister {
  Map<String, dynamic> _models = {
    'user': User(),

    'special_widgets': SpecialWidgets(),
   
//!important - do not remove required for program generation
  };

  dynamic instance(String model) => _models[model];
}
